spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-service}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  transaction:
    default-timeout: 30

  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true

logging:
  level:
    org.springframework.jdbc: TRACE
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

app:
  fetch-interval: 10000 #10 секунд

management:
  endpoints:
    web:
      exposure:
        include: "*" # Включает все web endpoints Actuator
  endpoint:
    mappings:
      access: unrestricted
    health:
      access: unrestricted