create table "feeds" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(50),
    "url" VARCHAR(1000) UNIQUE,
    "enabled" BOOLEAN,
    "last_fetched" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "news" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guid" VARCHAR(255) NOT NULL UNIQUE,
    "author" VARCHAR(255),
    "title" VARCHAR(255) NOT NULL,
    "link" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "pub_date" TIMESTAMP WITH TIME ZONE NOT NULL,
    "enclosure_url" VARCHAR(255),
    "enclosure_type" VARCHAR(50),
    "enclosure_length" BIGINT,
    "category" VARCHAR(255),
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "feed_id" BIGINT NOT NULL,
    CONSTRAINT "fk_feed" FOREIGN KEY ("feed_id") REFERENCES "feeds"("id")
);

insert into "feeds" ("name", "url", "enabled") values ('techcrunch', 'https://techcrunch.com/feed/', true),
('theverge', 'https://www.theverge.com/rss/index.xml', true),
('wired', 'https://www.wired.com/feed/rss', true),
('arstechnica', 'https://arstechnica.com/feed/', true),
('zdnet', 'https://www.zdnet.com/news/rss.xml', true),
('venturebeat', 'https://venturebeat.com/feed/', false),
('computerweekly', 'https://www.computerweekly.com/rss/All-Computer-Weekly-content.xml',false),
('techradar', 'https://www.techradar.com/rss', false),
('engadget', 'https://www.engadget.com/rss.xml', false),
('technologyreview', 'https://www.technologyreview.com/feed/', false);
